default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "password" } %>
  host: <%= ENV.fetch("DB_HOST") { "localhost" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>


development:
  <<: *default
  database: mydiary_development

test:
  <<: *default
  database: mydiary_test

production:
  primary: &primary_production
    <<: *default
    database: mydiary_production
    username: <%= ENV.fetch("DB_USERNAME") { "mydiary" } %>
    password: <%= ENV["MYDIARY_DATABASE_PASSWORD"] %>


  cache:
    <<: *primary_production
    database: mydiary_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: mydiary_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: mydiary_production_cable
    migrations_paths: db/cable_migrate